# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-30 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0032_merge_20181122_1527'),
        ('sessao', '0032_merge_20181126_1400'),
    ]

    operations = [
    ]
